SELECT * FROM customer LIMIT 20;

-- Total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
/* RESULT: Revenue collected through male customers ($157,890) is 
   higher than that collected through female customers ($75,191). */

-- Customers who still spent more than the average purchase amount despite using a discount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
	AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
/* RESULT: 839 customers spent more than the average purchase amount ($59.76) despite using a discount. */

-- Top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating)::numeric, 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
/* RESULT: Gloves (3.86), Sandals (3.84), Boots (3.82), Hats (3.80),
   and Skirts (3.78) are the top 5 products that secured the highest average
   review rating. */

-- Comparing average purchase amounts between Standard and Express Shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;
/* RESULT: Compared to Standard Shipping ($58.46), Express Shipping resulted in 
   the collection of a higher average amount ($60.48). This implies that customers
   seem to prefer Express Shipping over the other. */

-- Comparing average spending and total revenue between subscribers and non-subscribers
SELECT subscription_status,
	   COUNT(customer_id) AS total_customers,
	   ROUND(AVG(purchase_amount),2) AS avg_spend,
	   ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;
/* RESULT: Given among all customers, there are 1053 subscribers, having a 
   lower average spend ($59.49) and total collected revenue ($62,645) compared
   to the 2847 non-subscribers who spent $59.87 on average, and the total revenue
   collected via them was considerably higher ($170,436). */

-- Top 5 products with the highest percentage of purchases with discounts applied
SELECT item_purchased,
	   ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
	   		/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
/* RESULT: Hats (50%), Sneakers (49%), Coats (49%), Sweaters (48%), and
   Pants (47%) are the top product category by percentage of purchases with discounts applied. */

-- Classifying customers into New, Returning, and Loyal based on their
-- total number of previous purchases, and showing the count of each segment
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
/* RESULT: The number of loyal customers (3116) is higher than those that are
   either returning (701) or new (83). */

-- Top 3 most purchased products within each category
WITH item_count AS (
SELECT category,
	   item_purchased,
	   COUNT(customer_id) AS total_orders,
	   ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;
/* RESULT:
   - Most purchased under 'Accessories': Jewelry (171), Sunglasses (161), Belts (161)
   - Most purchased under 'Clothing': Blouse (171), Pants (171), Shirts (169)
   - Most purchased under 'Footwear': Sandals (160), Shoes (150), sneakers (145)
   - Most purchased under 'Outerwear': Jackets (163), Coats (161) */
   
-- Likelihood of customers who are repeat buyers (more than 5 previous purchases) being subscribers as well
SELECT subscription_status,
	   COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
/* RESULT: The likelihood of repeat buyers being subscribers is fairly low, given
   only 958 repeat buyers subscribed to the company's services compared to
   2518 repeat buyers who have not subscribed. */

-- Revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
/* RESULT: Young adults are observed to make more or comparatively expensive 
   purchases, contributing to a higher revenue ($62,143) than the Middle-aged (59,197),
   Adults ($55,978), and Senior ($55,763) age groups. */